### ISSUE TITLE
JavaFX Problem running on macOS Monterey with OpenJDK

### ISSUE THREAD

**Issue by rberger** [Eugene-Mark/bigdata-file-viewer#30]
When I try to run `BigdataFileViewer-1.3-SNAPSHOT-jar-with-dependencies.jar` I get the error:

```
java -jar Downloads/BigdataFileViewer-1.3-SNAPSHOT-jar-with-dependencies.jar
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
...
```

And with `BigdataFileViewer-1.1.1-SNAPSHOT-jar-with-dependencies.jar` I get:

```
 java -jar Downloads/BigdataFileViewer-1.1.1-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
...
```

Running macOS Monterey on an intel iMac 2020 and tried with openjdk 11 and 17

I believe the issue may be that those distributions don't include JavaFX libraries? I don't know how to correct for that though.

**Comment by sriyaj** [comment]
Same here. Exactly same errors for both libs. 

I tried on MacBook Pro (16-inch, 2019), Intel Core i7 on JDK 8 and 11

**Comment by jayaku** [comment]
Same here. Exactly same errors for both libs.

I tried on MacBook Pro (16-inch, 2019), Intel Core i7 on JDK 8 and 11

**Comment by a-agmon** [comment]
Also having the same issue

**Comment by sfanous** [comment]
I ran into the same issue. Resolved as follows

```
brew tap bell-sw/liberica
brew install --cask bell-sw/liberica/liberica-jdk18-full

java -jar BigdataFileViewer-1.3-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by Eugene-Mark** [comment]
@rberger Yes you're right, `Graphics Device initialization failed for :  es2, sw` shows that the library javafx is missing. Please make sure that you have javafx installed on your machine. As for the issue you met with `BigdataFileViewer-1.1.1-SNAPSHOT-jar-with-dependencies.jar`, it's a known issue and has been fixed by later version.

**Comment by Eugene-Mark** [comment]
@rberger @jayaku @a-agmon  The issue you met is because the lacking of javafx on you local env, please try install javafx firstly. At the same time, the process to make sure javafx installed correctly might be a little annoying. Based on that, I'm considering release another version of BDF without the dependency to javafx. Thanks for your comment here.
